name: Tests

on:
  push:
    branches: [ development ]

  workflow_dispatch:
  
jobs:
  build:
  
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: ESLint
        run: npm run lint
