name: Deployment for PRODUCTION

on:
  
  pull_request:
    branches: [ master ]

  workflow_dispatch:
  
jobs:
  build:
  
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          npm install
          npm install -g firebase-tools

      - name: Build
        run: npm run build
        
      - name: Deploy w/Firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
